/** generated by png2c from rgb.png .
 *
  * @file  
  * out array generated. 
*/



#include "png2c_raw_format.h"



extern const unsigned char out_RAWDATA[]; /* forward declaration */
extern const ImgData_t Img_out;   /* Extern declaration  */
