/** generated by png2c from rgb.png .
 *
  * @file  
  * rgb array generated. 
*/



#include "png2c_raw_format.h"



extern const unsigned char rgb_RAWDATA[]; /* forward declaration */
extern const ImgData_t Img_rgb;   /* Extern declaration  */
