/** generated by png2c from tb.png .
 *
  * @file  
  * tb array generated. 
*/



#include "png2c_raw_format.h"



extern const unsigned char tb_RAWDATA[]; /* forward declaration */
extern const ImgData_t Img_tb;   /* Extern declaration  */
